VIDEO_MEMORY_PROMPT = (
    "Watch this entire passive human egocentric video to build a reusable "
    "navigation memory of one indoor environment. The person is wandering "
    "naturally rather than demonstrating a particular task or following a "
    "clean route. This is not a general video summary: the memory will later "
    "help a mobile robot navigate when its target may initially be outside "
    "its camera view.\n\n"
    "Build a navigation-oriented understanding of the scene. Describe "
    "recognizable regions and place boundaries; stable visual landmarks; "
    "entrances, exits, corridors, openings, and traversable connections; and "
    "the sequence of observed transitions between regions. For each useful "
    "transition, record the visual cues that indicate where to turn or move, "
    "what should become visible next, and how progress or a wrong branch could "
    "be recognized. Identify revisited regions and recurring hubs even when "
    "they are seen from different headings.\n\n"
    "Also inspect the video systematically for small, portable, or visually "
    "subtle objects that a future object-goal navigation task could request. "
    "Do not record only large landmarks. For every actually observed small "
    "object that can be distinguished, describe its appearance and object "
    "category as specifically as the evidence permits, the region where it "
    "appears, the table/counter/shelf/container or other support surface it is "
    "on or near, and its position relative to stable nearby landmarks. Include "
    "the best supporting timestamp or time interval and note whether the "
    "object is seen from multiple views. Preserve uncertain identity, "
    "ambiguous instances, partial occlusion, and weak visibility rather than "
    "turning them into confident claims. Keep these small-object observations "
    "connected to the place and transition memory so a later planner can first "
    "navigate to the surrounding region or support surface and then search for "
    "the object.\n\n"
    "Account for the later robot camera having a different height and viewpoint "
    "from the human camera: prefer semantic and appearance cues that are likely "
    "to remain recognizable across embodiments. Use timestamps when they help "
    "recover evidence. Distinguish what is directly observed from spatial or "
    "directional inference.\n\n"
    "Preserve uncertainty and alternative route interpretations explicitly. Produce "
    "clear, detailed navigation memory that another vision-language model can "
    "read later together with a robot camera image and an arbitrary navigation "
    "or mobile-manipulation task."
)

MANIPULATION_EVENTS_PROMPT = (
    "You are labelling a passive egocentric video of a person moving through "
    "an indoor environment. The frames below are consecutive samples from one "
    "short window in which the camera wearer was mostly standing still. Decide "
    "whether, inside this window, the person manipulates a physical object "
    "with their hand or hands: reaching for, grasping, lifting, placing, "
    "opening, or handing over a real object such as a can, cup, bottle, box, "
    "tool, door handle, or drawer.\n\n"
    "For every such manipulation report:\n"
    "- object: a short noun phrase naming the manipulated object as "
    "specifically as the frames allow (for example \"can\" or \"blue mug\").\n"
    "- hand: which hand touches the object: \"left\", \"right\", or \"both\".\n"
    "- t_ready_s: the timestamp, in seconds on the video clock printed above "
    "each frame, of the LAST frame before the hand starts moving toward the "
    "object. At that moment the person is already standing where the "
    "manipulation will happen, in their docked stance, with the object within "
    "reach and the body and head essentially at rest.\n"
    "- t_grasp_s: the timestamp of the first frame in which the hand makes "
    "contact with the object.\n"
    "- confidence: a number from 0 to 1.\n"
    "- notes: one short sentence of evidence (what is visible, where the "
    "object is).\n\n"
    "Use only timestamps that appear in this window and keep t_ready_s <= "
    "t_grasp_s. Handling a phone, tablet, watch, or any other screen, "
    "adjusting glasses or clothing, gesturing, touching a wall or railing "
    "while walking, and looking at something without reaching for it are NOT "
    "manipulation events. If no physical object is manipulated in this "
    "window, return exactly {\"events\": []}.\n\n"
    "Respond with STRICT JSON only, no prose and no code fences, matching "
    "this shape:\n"
    "{\"events\": [{\"object\": \"can\", \"hand\": \"right\", \"t_ready_s\": "
    "16.5, \"t_grasp_s\": 19.0, \"confidence\": 0.8, \"notes\": \"...\"}]}"
)
